### ISSUE TITLE
垂直水平居中

### ISSUE THREAD

**Issue by bowenjun** [bowenjun/soon#2]
```html
<div class="parent">
  <div class="child"></div>
</div>
```

### 1

```css
.parent {
    display: flex;
    align-items: center;
    justify-content: center;
}
```

### 2

```css
.parent {
    display: grid;
}
.child {
    justify-self: center;
    align-self: center;
}
```

### 3

```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
}
```
